# 这里配置nacos相关配置
spring:
  # 上面nacos中配置文件其后缀为-dev表示激活后缀为dev的配置文件，若这里配置的是prod则配置文件名称为whisper-system-prod.yaml
  profiles:
    active:
      - dev

  # nacos配置
  cloud:
    nacos:
      # 配置中心
      config:
        enabled: true
        server-addr: xx.x.x.x:8848
        # 配置文件名称后缀，如：whisper-system-dev.yaml
        file-extension: yaml
        # 命名空间，这里是开发环境，若是上面的profiles后缀设置为其他，如：配置为prod则需要将该命名空间改为prod这个后缀文件所在的命名空间
        namespace: x
        username: xx
        password: xxx
      # 服务发现
      discovery:
        server-addr: xx.x.x.x:8848
        namespace: x
        username: xx
        password: xxx

  #关闭SpringBoot的banner
  main:
    banner-mode: off
